### ISSUE TITLE
mdns-resolver conflicts with avahi-daemon

### ISSUE THREAD

**Issue by shanemeagher** [shanemeagher/service.librespot#1]
When starting addon for first time in discovery mode, mdns-responder panics as it cannot access port 5353 which is already used by avahi-daemon.

Currently, have to kill avahi-daemon, restart addon and connect for first time and restart avahi-daemon. Subsequently starting the addon uses the cache.

[librespot_(20170222)_discovery_fail.txt](https://github.com/shanemeagher/service.librespot/files/844307/librespot_.20170222._discovery_fail.txt)

**Comment by shanemeagher** [comment]
It seems that LibreELEC is configured to run avahi-daemon with the option `disallow-other-stacks=yes` enabled. Reloading avahi-daemon with `disallow-other-stacks=no` fixes the problem however this isn't a permanent fix.

**Comment by plietar** [comment]
Relevant issue: https://github.com/plietar/librespot/issues/95
I've changed my mind since then, librespot should be able to use avahi rather than its internal mDNS implementation. This should solve your problems.

**Comment by shanemeagher** [comment]
Thanks @plietar 
I've tried using joerg-krause's code on the current master and made some fixes to account for changes since he wrote it but as my rust (and coding in general) is not great, I've hit a roadblock when adding the [rust-dns-sd](https://github.com/plietar/rust-dns-sd) equivalent to `_svc: mdns::Service` at
[/src/authentication/discovery.rs#L205](https://github.com/plietar/librespot/blob/master/src/authentication/discovery.rs#L205). Any tips?

Here's what I've gotten so far (ignore the .txt at the end of the filename).
[discovery.rs](https://github.com/shanemeagher/service.librespot/files/869791/discovery.rs.txt)

**Comment by shanemeagher** [comment]
Commit 016bc87 adds option to use a username and password with discovery disabled. This is enabled by default and acts as a workaround for avahi-daemon conflict.

**Comment by shanemeagher** [comment]
https://github.com/plietar/librespot/pull/201/files provides for building with support for external avahi support. This has been incorporated into the addon on LibreELEC repo.
